# Generated by Django 4.2.7 on 2023-11-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500, null=True)),
                ('created_at', models.DateField(null=True)),
            ],
        ),
    ]
