# Generated by Django 4.2.7 on 2023-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
